### ISSUE TITLE
Throttling limit updates

### ISSUE THREAD

**Issue by mattmillerai** [audiobridge/freesound-python#3]
When running a test I saw this error:
freesound.FreesoundException: <FreesoundException: code=429, detail="{u'detail': u'Request was throttled because of exceeding a request limit rate (60/minute)'}">

We need to put in a limiter in the code to prevent this from running more than 60 per minute (it would be great to make this a configurable parameter in the event that we ultimately get a higher limit at some point). We could use something like 'sleep' or track the elapsed time of the script and the number of API calls made and pause the script accordingly so it runs without interruption.

**Comment by girishasitsolutions** [comment]
I pull your changes in script. Its working fine. Thanks!
