### ISSUE TITLE
UTF-8 Issues

### ISSUE THREAD

**Issue by mattmillerai** [audiobridge/freesound-python#4]
I am receiving this error when running page 1 for the search key 'tired'. Specifically it is the sound with Freesound ID 378346. The error is:

`mysql.connector.errors.DatabaseError: 1366 (HY000): Incorrect string value: '\xC4\x8Dka.w...' for column 'name' at row 1`

And the JSON payload from that data is here:
https://pastebin.com/Uz5XDSEL

As you can see, in the URL there is the character č which I'm guessing is causing issues when saving to the DB. I'm guessing we just need to change the encoding on the DB column.

**Comment by girishasitsolutions** [comment]
Thats right!
I convert collections of both tables and now 378346 record inserted correctly.
ALTER DATABASE db_freesound CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `search_keys` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `tbl_sounds` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

**Comment by mattmillerai** [comment]
Can you add this character set assignment to the main SQL file so when we build the DB, it will build it with the right encoding?

**Comment by mattmillerai** [comment]
Works great. I've updated the SQL file and will do a pull request to reference this. Thanks!
