### ISSUE TITLE
Ability to detect for 429 error within main script file

### ISSUE THREAD

**Issue by mattmillerai** [audiobridge/freesound-python#8]
We need the ability to detect if the status code returned is a 429 error code. Ideally, if a 429 is returned (which is a throttling error), I would like us to sleep the script for the appropriate time and then have it continue, rather than error out. This way we can simply leave the script running and it will control itself depending on the API response.

**Comment by girishasitsolutions** [comment]
I commit 2 code. one I just change in core file and 2nd I write code in cronjob file for throttle error to sleep 24hrs on an error and resume again with same query. Please review.

**Comment by mattmillerai** [comment]
I can't find these commits. Can you link to them?

**Comment by girishasitsolutions** [comment]
Please check now

**Comment by mattmillerai** [comment]
This still isn't working great. When it exceeds the 60/minute throttle limit, it sleeps for 24 hours. I do have a piece of the script that tries to control so it doesn't go over the limit but in some cases it still happens. I was able to capture the JSON payload returned:

{"detail":"Request was throttled because of exceeding a request limit rate (60/minute)"}

I propose that we inspect JSON payload return if it is a 429 error and see if it contains the string '60/minute' and if so, we rest for 1 minute. If we get a 429 error that doesn't contain that string, then we rest for 24 hours.

Let me know if this makes sense. Thanks!

**Comment by girishasitsolutions** [comment]
Ok. i will check this shortly and update you

**Comment by girishasitsolutions** [comment]
Please check it again.

**Comment by mattmillerai** [comment]
Works great, thanks!
